- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: true
      changed_when: False

  tasks:
    - name: include tasks at tasks folder
      include_tasks:
        file: tasks/packages.yml
